# Generated by Django 5.2.8 on 2026-01-23 14:17

import avtozapchasti_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.FilePathField(path=avtozapchasti_app.models.item_discription_path)),
                ('material', models.CharField(max_length=20)),
                ('spare_parts_type', models.CharField(max_length=20)),
                ('spare_parts_color', models.CharField(max_length=20)),
            ],
        ),
    ]
