# Generated by Django 5.2.8 on 2026-01-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtozapchasti_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
