# Generated by Django 5.2.8 on 2026-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtozapchasti_app', '0002_remove_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=87879879),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default=878787, upload_to=''),
            preserve_default=False,
        ),
    ]
