# Generated by Django 5.2.8 on 2026-05-08 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtozapchasti_app', '0003_item_description_item_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='spare_parts_type',
            field=models.CharField(choices=[('bodywork', 'кузов'), ('fasteners', 'крепёж'), ('pendant', 'подвеска'), ('heating_and_ventilation', 'отопление и вентиляция'), ('steering_control', 'рулевое управление'), ('engine', 'двигатель'), ('salon', 'салон'), ('cooling_system', 'система охлождения'), ('fuel_system', 'топливная система'), ('brake_system', 'тормозная система'), ('transmission', 'трансмиссия'), ('filters', 'фильтры'), ('undercarriag', 'ходовая часть'), ('electrics', 'электрика'), ('summer_tires', 'летние шины'), ('winter_tires', 'зимние шины'), ('alloy_discs', 'литые диски'), ('tamped_discs', 'штампованные диски'), ('forged_discs', 'кованые диски'), ('passenger_car_batteries', 'легковые аккумуляторы'), ('cargo_batteries', 'грузовые аккумуляторы'), ('bike_batteries', 'мотоаккумуляторы'), ('cigarette_lighter_wires', 'провода прикуривания'), ('engine_oils', 'моторные масла'), ('brake_fluid', 'тормозная жидкость'), ('antifreeze', 'антифриз'), ('transmission_oil', 'трансмиссионная масло'), ('distilled_water', 'дистиллированная вода')], max_length=25),
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
