# Generated by Django 6.0.5 on 2026-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtozapchasti_app', '0004_alter_item_spare_parts_type_emailcode_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
